"""Pydantic data models used across SeatTrellis."""

from seattrellis.models.layout import AdjacencyConfig, ClassroomLayout, SeatNode
from seattrellis.models.candidate import (
    CandidatePlan,
    CandidateSet,
    HardConstraintSummary,
    MultiSolveOptions,
    PlanComparisonEntry,
    PlanComparisonReport,
    PlanScore,
    ScoreBreakdown,
    ScoreDimension,
)
from seattrellis.models.history import (
    FairnessReport,
    NeighborRelationType,
    PairHistory,
    PairHistoryRecord,
    PairHistoryReport,
    SeatHistory,
    SeatHistoryRecord,
    SeatPositionCategory,
    StudentPairHistory,
    StudentSeatHistory,
)
from seattrellis.models.rules import (
    AvoidRecentNeighborsRule,
    FairRotationRule,
    FixedSeatRule,
    HardRules,
    MinDistanceRule,
    PairRule,
    RuleSet,
    SoftRules,
    WeightedRule,
)
from seattrellis.models.snapshot import SeatAssignment, SeatingSnapshot
from seattrellis.models.student import Student

__all__ = [
    "AdjacencyConfig",
    "CandidatePlan",
    "CandidateSet",
    "ClassroomLayout",
    "AvoidRecentNeighborsRule",
    "FairRotationRule",
    "FairnessReport",
    "FixedSeatRule",
    "HardRules",
    "HardConstraintSummary",
    "MinDistanceRule",
    "MultiSolveOptions",
    "NeighborRelationType",
    "PairHistory",
    "PairHistoryRecord",
    "PairHistoryReport",
    "PairRule",
    "PlanComparisonEntry",
    "PlanComparisonReport",
    "PlanScore",
    "RuleSet",
    "SeatAssignment",
    "SeatHistory",
    "SeatHistoryRecord",
    "SeatNode",
    "SeatPositionCategory",
    "SeatingSnapshot",
    "ScoreBreakdown",
    "ScoreDimension",
    "SoftRules",
    "Student",
    "StudentPairHistory",
    "StudentSeatHistory",
    "WeightedRule",
]
