//! Embed the production React workbench into the native application.
//!
//! The development server still prefers `SEATTRELLIS_WEB_STATIC` and the
//! checkout's `src/seattrellis/web_static` directory.  Release binaries need
//! a second path, though: a user should be able to copy the executable away
//! from the source tree and start it without installing Node or Python.  This
//! small build script turns the frontend files into `include_bytes!` entries
//! so the HTTP server can serve them directly from the binary.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by Cargo"),
    );
    let web_root = manifest_dir.join("../../src/seattrellis/web_static");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));

    let mut files = Vec::new();
    collect_files(&web_root, &web_root, &mut files).unwrap_or_else(|error| {
        panic!(
            "cannot embed React workbench from {}: {error}; build the frontend first",
            web_root.display()
        )
    });
    files.sort_by(|left, right| left.0.cmp(&right.0));

    // A source map is useful to frontend developers but is not loaded by the
    // application at runtime.  Omitting it keeps the standalone binary small
    // without changing the production workbench.
    files.retain(|(relative, _)| relative.extension().and_then(|ext| ext.to_str()) != Some("map"));

    let destination = out_dir.join("embedded_web_assets.rs");
    let mut generated = "// Generated by app/build.rs; do not edit.\n".to_string()
        + "pub static EMBEDDED_WEB_ASSETS: &[(&str, &[u8])] = &[\n";
    for (relative, absolute) in files {
        let relative = relative.to_string_lossy().replace('\\', "/");
        let absolute = rust_string_literal(&absolute.to_string_lossy());
        generated.push_str(&format!(
            "    ({}, include_bytes!({})),\n",
            rust_string_literal(&relative),
            absolute
        ));
    }
    generated.push_str("];\n");

    fs::write(&destination, generated).unwrap_or_else(|error| {
        panic!(
            "cannot write embedded asset manifest {}: {error}",
            destination.display()
        )
    });

    // Re-run when a frontend file changes, not only when the directory entry
    // changes.  Hidden files are intentionally ignored by `collect_files`.
    println!("cargo:rerun-if-changed={}", web_root.display());
    for (_, path) in collect_files_for_rerun(&web_root) {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn collect_files(
    root: &Path,
    current: &Path,
    files: &mut Vec<(PathBuf, PathBuf)>,
) -> std::io::Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        let name = entry.file_name();
        if name.to_string_lossy().starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_files(root, &path, files)?;
        } else if path.is_file() {
            let relative = path
                .strip_prefix(root)
                .expect("asset is below the workbench root")
                .to_path_buf();
            files.push((relative, path));
        }
    }
    Ok(())
}

fn collect_files_for_rerun(root: &Path) -> Vec<(PathBuf, PathBuf)> {
    let mut files = Vec::new();
    let _ = collect_files(root, root, &mut files);
    files
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
