blank_issues_enabled: true
contact_links:
  - name: README (中文)
    url: https://github.com/FrankFu916/seattrellis/blob/main/README.md
    about: Please read the README and docs before opening an issue.
  - name: README (English)
    url: https://github.com/FrankFu916/seattrellis/blob/main/README.en.md
    about: Please read the README and docs before opening an issue.
