// Rule registry consumption layer (M5-A7, M3-01/M6-02).
//
// The Rust rule registry (generated by xtask into ruleRegistry.generated.ts)
// is the single source of truth for rule metadata. The workbench renders
// rule controls from these specs instead of hand-written rule lists; the
// self-compiled rule logic in generation.ts is a registered M6 removal.
//
// This module is the consumption seam: lookups, category helpers and a gate
// that keeps every rule id used by the workbench inside the registry.

import { RULE_SPECS, type RuleSpec } from "../api/ruleRegistry.generated";

export type RuleCategory = "hard" | "soft";

export function findRule(id: string): RuleSpec | undefined {
  return RULE_SPECS.find((spec) => spec.id === id);
}

export function rulesByCategory(category: RuleCategory): RuleSpec[] {
  return RULE_SPECS.filter((spec) => spec.category === category);
}

export function requireRule(id: string): RuleSpec {
  const spec = findRule(id);
  if (!spec) {
    throw new Error(`RuleSpec not found in the Rust registry: ${id}`);
  }
  return spec;
}

export const ALL_RULE_IDS: ReadonlySet<string> = new Set(
  RULE_SPECS.map((spec) => spec.id),
);
