"""Stable Streamlit widget keys used by tests and workflow code."""

QUICK_LOAD_DEMO_BUTTON = "quick_load_demo"
QUICK_REPAIR_BUTTON = "quick_repair"
QUICK_SWAP_BUTTON = "quick_swap_students"
QUICK_UNDO_BUTTON = "quick_edit_undo"
QUICK_REDO_BUTTON = "quick_edit_redo"
QUICK_GENERATE_BUTTON = "quick_generate"
QUICK_CANDIDATE_COUNT_INPUT = "quick_candidate_count"
QUICK_EXPORT_FORMAT_SELECT = "quick_export_format"
QUICK_EXPORT_ALL_CANDIDATES_CHECKBOX = "quick_export_all_candidates"
QUICK_EXPORT_DOWNLOAD_ARTIFACT = "quick_export_download_artifact"
QUICK_EXPORT_DOWNLOAD_REPORT = "quick_export_download_report"

PROJECT_EXPORT_DOWNLOAD_ARTIFACT = "project_export_download_artifact"
PROJECT_EXPORT_DOWNLOAD_REPORT = "project_export_download_report"
PROJECT_REPAIR_BUTTON = "project_repair"
PROJECT_SWAP_BUTTON = "project_swap_students"
PROJECT_UNDO_BUTTON = "project_edit_undo"
PROJECT_REDO_BUTTON = "project_edit_redo"
