"""Stable Streamlit widget keys used by tests and workflow code."""

UI_LANGUAGE_SELECT = "ui_language_choice"
APP_WORKSPACE_SELECT = "app_workspace"

TEACHER_HOME_STATUS = "teacher_home_status"
TEACHER_CLASS_NAME_INPUT = "teacher_class_name"
TEACHER_ROSTER_UPLOAD = "teacher_roster"
TEACHER_ROSTER_STATUS = "teacher_roster_status"
TEACHER_ROOM_TEMPLATE_SELECT = "teacher_room_template"
TEACHER_ROOM_ROWS_INPUT = "teacher_room_rows"
TEACHER_ROOM_SEATS_PER_ROW_INPUT = "teacher_room_seats_per_row"
TEACHER_ROOM_AISLES_INPUT = "teacher_room_aisles"
TEACHER_ROOM_STATUS = "teacher_room_status"
TEACHER_GOAL_SELECT = "teacher_goal"
TEACHER_GENERATE_BUTTON = "teacher_generate"
TEACHER_SOLVE_STATUS = "teacher_solve_status"
TEACHER_RESULTS_STATUS = "teacher_results_status"
TEACHER_CANDIDATE_SELECT = "teacher_candidate_selector"
TEACHER_PUBLIC_EXPORT_PREPARE = "teacher_public_export_prepare"
TEACHER_PUBLIC_EXPORT_DOWNLOAD = "teacher_public_export_download"
TEACHER_INTERNAL_EXPORT_PREPARE = "teacher_internal_export_prepare"
TEACHER_INTERNAL_EXPORT_DOWNLOAD = "teacher_internal_export_download"
TEACHER_EXPORT_PREFIX = "teacher_export"

QUICK_LOAD_DEMO_BUTTON = "quick_load_demo"
QUICK_STEP_RADIO = "quick_step"
QUICK_CONFIG_UPLOAD = "quick_config"
QUICK_STUDENTS_UPLOAD = "quick_students"
QUICK_LAYOUT_UPLOAD = "quick_layout"
QUICK_PRESET_SELECT = "quick_preset"
QUICK_RULES_UPLOAD = "quick_rules"
QUICK_HISTORY_UPLOAD = "quick_history"
QUICK_CLEAR_UPLOADS_BUTTON = "quick_clear_uploads"
QUICK_RETAINED_UPLOADS_STATUS = "quick_retained_uploads"
QUICK_INSPECT_HISTORY_BUTTON = "quick_inspect_history"
QUICK_CANDIDATE_SELECT = "quick_candidate_selector"
QUICK_SOLVE_STATUS = "quick_solve_status"
QUICK_RESULTS_STATUS = "quick_results_status"
QUICK_REPAIR_BUTTON = "quick_repair"
QUICK_SWAP_BUTTON = "quick_swap_students"
QUICK_UNDO_BUTTON = "quick_edit_undo"
QUICK_REDO_BUTTON = "quick_edit_redo"
QUICK_EDIT_ACTION_SELECT = "quick_edit_action"
QUICK_EDIT_APPLY_BUTTON = "quick_edit_apply"
QUICK_LOCK_STUDENT_SELECT = "quick_lock_student"
QUICK_LOCK_STUDENT_BUTTON = "quick_toggle_student_lock"
QUICK_LOCK_SEAT_SELECT = "quick_lock_seat"
QUICK_LOCK_SEAT_BUTTON = "quick_toggle_seat_lock"
QUICK_BATCH_STUDENTS_SELECT = "quick_batch_students"
QUICK_BATCH_SEATS_SELECT = "quick_batch_seats"
QUICK_BATCH_MOVE_BUTTON = "quick_batch_move"
QUICK_CANVAS_MODE_SELECT = "quick_canvas_mode"
QUICK_GENERATE_BUTTON = "quick_generate"
QUICK_CANDIDATE_COUNT_INPUT = "quick_candidate_count"
QUICK_EXPORT_FORMAT_SELECT = "quick_export_format"
QUICK_EXPORT_ALL_CANDIDATES_CHECKBOX = "quick_export_all_candidates"
QUICK_EXPORT_DOWNLOAD_ARTIFACT = "quick_export_download_artifact"
QUICK_EXPORT_DOWNLOAD_REPORT = "quick_export_download_report"
QUICK_EXPORT_PREFIX = "quick_export"

PROJECT_EXPORT_DOWNLOAD_ARTIFACT = "project_export_download_artifact"
PROJECT_EXPORT_DOWNLOAD_REPORT = "project_export_download_report"
PROJECT_EXPORT_PREFIX = "project_export"
PROJECT_MODE_RADIO = "project_mode"
PROJECT_PATH_INPUT = "project_path_text"
PROJECT_PATH_STATUS = "project_path_status"
PROJECT_UPLOAD_INPUT = "project_upload"
PROJECT_INFO_BUTTON = "project_info"
PROJECT_INFO_STATUS = "project_info_status"
PROJECT_VALIDATE_BUTTON = "project_validate"
PROJECT_VALIDATE_STATUS = "project_validate_status"
PROJECT_STRICT_CHECKBOX = "project_strict"
PROJECT_USE_DEFAULT_CANDIDATES = "project_use_default_candidates"
PROJECT_CANDIDATE_COUNT_INPUT = "project_candidate_count"
PROJECT_SEED_ENABLED = "project_seed_enabled"
PROJECT_SEED_INPUT = "project_seed"
PROJECT_TIME_LIMIT_INPUT = "project_time_limit"
PROJECT_SOLVE_BUTTON = "project_solve"
PROJECT_SOLVE_STATUS = "project_solve_status"
PROJECT_RESULTS_STATUS = "project_results_status"
PROJECT_CANDIDATE_SELECT = "project_candidate_selector"
PROJECT_REPAIR_BUTTON = "project_repair"
PROJECT_SWAP_BUTTON = "project_swap_students"
PROJECT_UNDO_BUTTON = "project_edit_undo"
PROJECT_REDO_BUTTON = "project_edit_redo"
PROJECT_EDIT_ACTION_SELECT = "project_edit_action"
PROJECT_EDIT_APPLY_BUTTON = "project_edit_apply"
PROJECT_LOCK_STUDENT_SELECT = "project_lock_student"
PROJECT_LOCK_STUDENT_BUTTON = "project_toggle_student_lock"
PROJECT_LOCK_SEAT_SELECT = "project_lock_seat"
PROJECT_LOCK_SEAT_BUTTON = "project_toggle_seat_lock"
PROJECT_BATCH_STUDENTS_SELECT = "project_batch_students"
PROJECT_BATCH_SEATS_SELECT = "project_batch_seats"
PROJECT_BATCH_MOVE_BUTTON = "project_batch_move"
PROJECT_CANVAS_MODE_SELECT = "project_canvas_mode"


def export_prepare_key(export_prefix: str, output_format: str) -> str:
    """Return the widget key for preparing an export."""

    return f"{export_prefix}_prepare_{output_format}"


def export_prepared_download_key(export_prefix: str) -> str:
    """Return the widget key for downloading a prepared export."""

    return f"{export_prefix}_download_prepared"


def export_prepared_state_key(export_prefix: str) -> str:
    """Return the session-state key for an on-demand export."""

    return f"{export_prefix}_prepared_download"


def widget_region_key(widget_key: str) -> str:
    """Return a stable container key for browser automation and styling."""

    return f"{widget_key}_region"
