// Generated by `cargo run -p xtask -- contract ts` — DO NOT EDIT.
// Source of truth: xtask/src/spec.rs (M1-06).
// Typed companion for the loopback API. The workbench (client.ts)
// remains the wired client; this file is the drift-checked contract
// seed that M6 converges onto.

let sessionToken: string | null = null;

export function setSessionToken(token: string | null): void {
  sessionToken = token;
}

async function call<T>(path: string, init?: RequestInit): Promise<T> {
  const headers = new Headers(init?.headers);
  headers.set("Accept", "application/json");
  if (sessionToken) headers.set("Authorization", `Bearer ${sessionToken}`);
  const response = await fetch(path, { ...init, headers });
  if (!response.ok) {
    throw new Error(`SeatTrellis API ${response.status}: ${await response.text()}`);
  }
  return (await response.json()) as T;
}

export const API_ROOT = "/api/v1";

export interface HealthResponse {
  api_version: string;
  service: string;
  status: string;
}

export interface SessionResponse {
  api_version: number;
  session_token: string;
}

export interface CoreSolveRequest {
  api_version: number;
  student_count: number;
  seat_positions: number[][];
  edges?: number[][];
  fixed_seats?: number[][];
  must_be_adjacent?: number[][];
  cannot_be_adjacent?: number[][];
  min_distance?: unknown[];
  seed?: number;
  students?: unknown[];
  rules?: Record<string, unknown>;
  layout?: Record<string, unknown>;
  history?: Record<string, unknown>;
  pair_history?: Record<string, unknown>;
  time_limit_seconds?: number;
}

export interface CoreSolveResponse {
  api_version: number;
  feasible: boolean;
  status: SolveStatus;
  assignment: number[][];
  attempts_used: number;
  hard_constraints_satisfied: boolean;
  total_cost: number | null;
}

export interface GenerateClassRequest {
  draft: {
    students: unknown[];
    room: { template_id?: string; layout?: Record<string, unknown> };
    goal: Record<string, unknown>;
    history_snapshots?: unknown[];
  };
  options?: { seed?: number; candidate_count?: number };
}

export interface CandidateSummary {
  candidate_id: string;
  recommended: boolean;
  total_score: number;
}

export type SolveStatus =
  | "Solved"
  | "ProvenInfeasible"
  | "Timeout"
  | "Unknown"
  | "InvalidInput"
  | "Cancelled"
  | "InternalError";

export interface GenerateClassSolvedResponse {
  status: "Solved";
  feasible: true;
  class_name: string;
  goal: Record<string, unknown>;
  warnings: string[];
  recommended_candidate_id: string;
  candidates: CandidateSummary[];
  editor: EditorState;
}

export interface GenerateClassUnsolvedResponse {
  status: Exclude<SolveStatus, "Solved" | "InvalidInput" | "InternalError">;
  feasible: false;
  class_name: string;
  goal: Record<string, unknown>;
  warnings: string[];
  recommended_candidate_id: null;
  candidates: [];
  editor: null;
  message_key: string;
  recoverable: boolean;
  suggested_action: string;
}

export type GenerateClassResponse =
  | GenerateClassSolvedResponse
  | GenerateClassUnsolvedResponse;

export interface GenerateRotationRequest extends GenerateClassRequest {
  period_count: number;
  period_labels?: string[];
}

export interface GenerateRotationSolvedResponse {
  status: "Solved";
  feasible: true;
  class_name: string;
  warnings: string[];
  rotation_plan: Record<string, unknown>;
  editor: EditorState;
  failed_period: null;
}

export interface GenerateRotationUnsolvedResponse {
  status: Exclude<SolveStatus, "Solved" | "InvalidInput" | "InternalError">;
  feasible: false;
  class_name: string;
  warnings: string[];
  rotation_plan: null;
  editor: null;
  failed_period: number;
  message_key: string;
  recoverable: boolean;
  suggested_action: string;
}

export type GenerateRotationResponse =
  | GenerateRotationSolvedResponse
  | GenerateRotationUnsolvedResponse;

export interface EditorStudentState {
  student_key: string;
  display_name: string;
  seat_id?: string;
  locked: boolean;
}

export interface EditorSeatState {
  seat_id: string;
  [key: string]: unknown;
}

export interface EditorState {
  kind: string;
  protocol_version: string;
  draft_id: string;
  revision: number;
  candidate_id?: string;
  undo_depth: number;
  redo_depth: number;
  students: EditorStudentState[];
  seats: EditorSeatState[];
}

export interface EditorCommandEnvelope {
  kind: string;
  protocol_version: string;
  command_id: string;
  draft_id: string;
  base_revision: number;
  action: string;
  operations?: unknown[];
}

export interface ExportDraftRequest {
  draft_id: string;
  format: "svg" | "html" | "print-html" | "png" | "pdf" | "excel" | "docx" | "pptx";
  template?: string;
  privacy?: string;
  orientation?: string;
  page_scale?: number;
  locale?: string;
  show_student_ids?: boolean;
}
export async function health(): Promise<HealthResponse> {
  return call<HealthResponse>(`${API_ROOT}/health`);
}
export async function fetchSession(): Promise<SessionResponse> {
  return call<SessionResponse>(`${API_ROOT}/session`);
}
export async function generateClass(
  request: GenerateClassRequest | CoreSolveRequest,
): Promise<GenerateClassResponse> {
  return call<GenerateClassResponse>(`${API_ROOT}/classes/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });
}
export async function generateRotation(
  request: GenerateRotationRequest,
): Promise<GenerateRotationResponse> {
  return call<GenerateRotationResponse>(`${API_ROOT}/classes/rotation`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });
}
export async function solveV2(
  request: CoreSolveRequest,
): Promise<CoreSolveResponse> {
  return call<CoreSolveResponse>("/api/v2/solve", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });
}
export async function fetchEditorState(
  draftId: string,
): Promise<EditorState> {
  return call<EditorState>(`${API_ROOT}/editing/drafts/${draftId}`);
}
export async function dispatchEditorCommand(
  draftId: string,
  command: EditorCommandEnvelope,
): Promise<EditorState> {
  return call<EditorState>(`${API_ROOT}/editing/drafts/${draftId}/commands`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(command),
  });
}
export async function exportDraft(
  request: ExportDraftRequest,
): Promise<Blob> {
  const response = await fetch(`${API_ROOT}/exports`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
    },
    body: JSON.stringify(request),
  });
  if (!response.ok) throw new Error(`SeatTrellis API ${response.status}`);
  return response.blob();
}
export async function listRecentProjects(
  root?: string,
  limit = 20,
): Promise<unknown> {
  const query = new URLSearchParams({ limit: String(limit) });
  if (root) query.set("root", root);
  return call<unknown>(`${API_ROOT}/projects/recent?${query}`);
}
