// Generated by `cargo run -p xtask -- contract rules` — DO NOT EDIT.
// Source of truth: crates/seattrellis-rules (M3-01).
// The React workbench renders rule controls from this registry; it
// never hard-codes rule lists (M6-02).

export interface RuleSpec {
           id: string;
           spec_version: number;
           category: "hard" | "soft";
           label: { zh: string; en: string };
           help: { zh: string; en: string };
           explanation: { zh: string; en: string };
           explanation_code: string;
           param_schema: Record<string, unknown>;
           defaults: Record<string, unknown>;
           objective?: { direction: string; weight_semantics: string; audit_version: number };
         }

export const RULE_SPECS: RuleSpec[] = [
  {
    "category": "hard",
    "defaults": {
      "seat_id": "",
      "student": ""
    },
    "explanation": {
      "en": "rule.fixed_seats.explanation",
      "zh": "rule.fixed_seats.explanation"
    },
    "explanation_code": "fixed_seat_conflict",
    "help": {
      "en": "rule.fixed_seats.help",
      "zh": "rule.fixed_seats.help"
    },
    "id": "fixed_seats",
    "label": {
      "en": "rule.fixed_seats.label",
      "zh": "rule.fixed_seats.label"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "seat_id": {
          "type": "string"
        },
        "student": {
          "type": "string"
        }
      },
      "required": [
        "student",
        "seat_id"
      ],
      "title": "FixedSeatParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "hard",
    "defaults": {
      "students": [
        "",
        ""
      ]
    },
    "explanation": {
      "en": "rule.must_be_adjacent.explanation",
      "zh": "rule.must_be_adjacent.explanation"
    },
    "explanation_code": "must_be_adjacent_unsatisfied",
    "help": {
      "en": "rule.must_be_adjacent.help",
      "zh": "rule.must_be_adjacent.help"
    },
    "id": "must_be_adjacent",
    "label": {
      "en": "rule.must_be_adjacent.label",
      "zh": "rule.must_be_adjacent.label"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "students": {
          "items": {
            "type": "string"
          },
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [
        "students"
      ],
      "title": "PairStudentsParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "hard",
    "defaults": {
      "students": [
        "",
        ""
      ]
    },
    "explanation": {
      "en": "rule.cannot_be_adjacent.explanation",
      "zh": "rule.cannot_be_adjacent.explanation"
    },
    "explanation_code": "cannot_be_adjacent_violated",
    "help": {
      "en": "rule.cannot_be_adjacent.help",
      "zh": "rule.cannot_be_adjacent.help"
    },
    "id": "cannot_be_adjacent",
    "label": {
      "en": "rule.cannot_be_adjacent.label",
      "zh": "rule.cannot_be_adjacent.label"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "students": {
          "items": {
            "type": "string"
          },
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [
        "students"
      ],
      "title": "PairStudentsParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "hard",
    "defaults": {
      "distance": 1.0,
      "metric": "graph",
      "students": [
        "",
        ""
      ]
    },
    "explanation": {
      "en": "rule.min_distance.explanation",
      "zh": "rule.min_distance.explanation"
    },
    "explanation_code": "min_distance_violated",
    "help": {
      "en": "rule.min_distance.help",
      "zh": "rule.min_distance.help"
    },
    "id": "min_distance",
    "label": {
      "en": "rule.min_distance.label",
      "zh": "rule.min_distance.label"
    },
    "param_schema": {
      "$defs": {
        "DistanceMetric": {
          "enum": [
            "euclidean",
            "graph"
          ],
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "distance": {
          "description": "Must be > 0 (validated at rule resolution, M3-03 precheck).",
          "format": "double",
          "type": "number"
        },
        "metric": {
          "$ref": "#/$defs/DistanceMetric",
          "default": "graph"
        },
        "students": {
          "items": {
            "type": "string"
          },
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [
        "students",
        "distance"
      ],
      "title": "MinDistanceParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "hard",
    "defaults": {
      "name": "",
      "separate": false,
      "students": []
    },
    "explanation": {
      "en": "rule.groups.explanation",
      "zh": "rule.groups.explanation"
    },
    "explanation_code": "group_conflict",
    "help": {
      "en": "rule.groups.help",
      "zh": "rule.groups.help"
    },
    "id": "groups",
    "label": {
      "en": "rule.groups.label",
      "zh": "rule.groups.label"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "separate": {
          "default": false,
          "description": "`true` = members must sit apart; `false` = members must sit together.",
          "type": "boolean"
        },
        "students": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "name",
        "students"
      ],
      "title": "GroupParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "weight": 1
    },
    "explanation": {
      "en": "rule.vision_front.explanation",
      "zh": "rule.vision_front.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.vision_front.help",
      "zh": "rule.vision_front.help"
    },
    "id": "vision_front",
    "label": {
      "en": "rule.vision_front.label",
      "zh": "rule.vision_front.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "WeightedRuleParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "weight": 1
    },
    "explanation": {
      "en": "rule.height_back.explanation",
      "zh": "rule.height_back.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.height_back.help",
      "zh": "rule.height_back.help"
    },
    "id": "height_back",
    "label": {
      "en": "rule.height_back.label",
      "zh": "rule.height_back.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "WeightedRuleParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "weight": 1
    },
    "explanation": {
      "en": "rule.randomize.explanation",
      "zh": "rule.randomize.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.randomize.help",
      "zh": "rule.randomize.help"
    },
    "id": "randomize",
    "label": {
      "en": "rule.randomize.label",
      "zh": "rule.randomize.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "WeightedRuleParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "weight": 1
    },
    "explanation": {
      "en": "rule.score_balance.explanation",
      "zh": "rule.score_balance.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.score_balance.help",
      "zh": "rule.score_balance.help"
    },
    "id": "score_balance",
    "label": {
      "en": "rule.score_balance.label",
      "zh": "rule.score_balance.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "WeightedRuleParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "avoid_repeating_categories": [
        "front",
        "back",
        "side",
        "corner",
        "near_window",
        "near_door",
        "near_ac"
      ],
      "enabled": false,
      "lookback": 4,
      "weight": 10
    },
    "explanation": {
      "en": "rule.fair_rotation.explanation",
      "zh": "rule.fair_rotation.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.fair_rotation.help",
      "zh": "rule.fair_rotation.help"
    },
    "id": "fair_rotation",
    "label": {
      "en": "rule.fair_rotation.label",
      "zh": "rule.fair_rotation.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "avoid_repeating_categories": {
          "default": [
            "front",
            "back",
            "side",
            "corner",
            "near_window",
            "near_door",
            "near_ac"
          ],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "lookback": {
          "default": 4,
          "format": "int32",
          "type": "integer"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "FairRotationParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "lookback": 4,
      "max_recent_count": 1,
      "relation_types": [
        "desk_mate",
        "adjacent_any"
      ],
      "weight": 10,
      "within_distance": 2
    },
    "explanation": {
      "en": "rule.avoid_recent_neighbors.explanation",
      "zh": "rule.avoid_recent_neighbors.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.avoid_recent_neighbors.help",
      "zh": "rule.avoid_recent_neighbors.help"
    },
    "id": "avoid_recent_neighbors",
    "label": {
      "en": "rule.avoid_recent_neighbors.label",
      "zh": "rule.avoid_recent_neighbors.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "lookback": {
          "default": 4,
          "format": "int32",
          "type": "integer"
        },
        "max_recent_count": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        },
        "relation_types": {
          "default": [
            "desk_mate",
            "adjacent_any"
          ],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        },
        "within_distance": {
          "default": 2,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "AvoidRecentNeighborsParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "cooling_period": 3,
      "enabled": false,
      "relation_types": [
        "desk_mate",
        "adjacent_any"
      ],
      "weight": 5,
      "within_distance": 2
    },
    "explanation": {
      "en": "rule.cooling.explanation",
      "zh": "rule.cooling.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.cooling.help",
      "zh": "rule.cooling.help"
    },
    "id": "cooling",
    "label": {
      "en": "rule.cooling.label",
      "zh": "rule.cooling.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "cooling_period": {
          "default": 3,
          "format": "int32",
          "type": "integer"
        },
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "relation_types": {
          "default": [
            "desk_mate",
            "adjacent_any"
          ],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "weight": {
          "default": 5,
          "format": "int32",
          "type": "integer"
        },
        "within_distance": {
          "default": 2,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "CoolingParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "direction": "high_front",
      "enabled": false,
      "weight": 1
    },
    "explanation": {
      "en": "rule.score_position.explanation",
      "zh": "rule.score_position.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.score_position.help",
      "zh": "rule.score_position.help"
    },
    "id": "score_position",
    "label": {
      "en": "rule.score_position.label",
      "zh": "rule.score_position.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$defs": {
        "ScoreDirection": {
          "enum": [
            "high_front",
            "high_back"
          ],
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "direction": {
          "$ref": "#/$defs/ScoreDirection",
          "default": "high_front"
        },
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "ScorePositionParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "enabled": false,
      "scope": "row",
      "weight": 1
    },
    "explanation": {
      "en": "rule.score_distribution.explanation",
      "zh": "rule.score_distribution.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.score_distribution.help",
      "zh": "rule.score_distribution.help"
    },
    "id": "score_distribution",
    "label": {
      "en": "rule.score_distribution.label",
      "zh": "rule.score_distribution.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$defs": {
        "DistributionScope": {
          "enum": [
            "row",
            "group"
          ],
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "scope": {
          "$ref": "#/$defs/DistributionScope",
          "default": "row"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "ScoreDistributionParam",
      "type": "object"
    },
    "spec_version": 1
  },
  {
    "category": "soft",
    "defaults": {
      "avoid_recent_repeats": true,
      "enabled": false,
      "history_lookback": 4,
      "learner_percentile": 0.25,
      "mentor_percentile": 0.75,
      "relation": "desk_mate",
      "weight": 10
    },
    "explanation": {
      "en": "rule.mentor_pairing.explanation",
      "zh": "rule.mentor_pairing.explanation"
    },
    "explanation_code": "soft_objective",
    "help": {
      "en": "rule.mentor_pairing.help",
      "zh": "rule.mentor_pairing.help"
    },
    "id": "mentor_pairing",
    "label": {
      "en": "rule.mentor_pairing.label",
      "zh": "rule.mentor_pairing.label"
    },
    "objective": {
      "audit_version": 1,
      "direction": "lower",
      "weight_semantics": "relative"
    },
    "param_schema": {
      "$defs": {
        "PairRelation": {
          "enum": [
            "desk_mate",
            "adjacent_any"
          ],
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "avoid_recent_repeats": {
          "default": true,
          "type": "boolean"
        },
        "enabled": {
          "default": false,
          "type": "boolean"
        },
        "history_lookback": {
          "default": 4,
          "format": "int32",
          "type": "integer"
        },
        "learner_percentile": {
          "default": 0.25,
          "format": "double",
          "type": "number"
        },
        "mentor_percentile": {
          "default": 0.75,
          "format": "double",
          "type": "number"
        },
        "relation": {
          "$ref": "#/$defs/PairRelation",
          "default": "desk_mate"
        },
        "weight": {
          "default": 1,
          "format": "int32",
          "type": "integer"
        }
      },
      "title": "MentorPairingParam",
      "type": "object"
    },
    "spec_version": 1
  }
];
