#!/usr/bin/env python3
"""Reject private/generated files in git and built distributions."""

from __future__ import annotations

import argparse
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path, PurePosixPath


PRIVATE_COMPONENTS = {
    "data",
    "exports",
    "outputs",
    "private",
    "real_classes",
    "real_students",
    "snapshots",
}
FORBIDDEN_NAMES = {".DS_Store", ".env"}
FORBIDDEN_IMAGE_SUFFIXES = {
    ".avif",
    ".heic",
    ".heif",
    ".icns",
    ".j2k",
    ".jp2",
    ".jxl",
}


def _unsafe_image_format(data: bytes) -> str | None:
    """Identify formats affected by the unpatched image-size build-time DoS.

    Docusaurus currently pulls image-size 2.0.2, whose ICNS, JPEG XL and
    HEIF-family parsers can loop forever on crafted input. Documentation
    assets are repository-controlled, so rejecting both their extensions and
    file signatures closes the reachable attack surface until upstream ships
    a patched dependency.
    """
    if data.startswith(b"icns"):
        return "ICNS"
    if data.startswith(b"\xff\x0a"):
        return "JPEG XL codestream"
    if data.startswith(b"\x00\x00\x00\x0cJXL \r\n\x87\n"):
        return "JPEG XL container"
    if data.startswith(b"\x00\x00\x00\x0cjP  \r\n\x87\n"):
        return "JPEG 2000"
    if len(data) >= 12 and data[4:8] == b"ftyp":
        brand = data[8:12]
        if brand in {
            b"avif",
            b"avis",
            b"heic",
            b"heix",
            b"hevc",
            b"hevx",
            b"mif1",
            b"msf1",
        }:
            return f"ISO BMFF ({brand.decode('ascii')})"
    return None


def _is_allowed_example_snapshot(path: PurePosixPath) -> bool:
    parts = path.parts
    # The synthetic parity corpus (fixtures/parity, generated by
    # scripts/gen_parity_fixtures.py) deliberately contains *.snapshot.json
    # files; it is synthetic test data, not real student data.
    if "fixtures" in parts and "parity" in parts:
        return True
    # The artifact-parity corpus (fixtures/artifact-parity) carries its own
    # outputs/ directory with synthetic compare/restore evidence files.
    if "fixtures" in parts and "artifact-parity" in parts:
        return True
    for index in range(len(parts) - 2):
        if parts[index : index + 2] == ("examples", "history"):
            return True
    return False


def _path_problem(raw_path: str) -> str | None:
    normalized = raw_path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    path = PurePosixPath(normalized)
    if path.name in FORBIDDEN_NAMES:
        return f"forbidden file name: {normalized}"
    if any(part in PRIVATE_COMPONENTS for part in path.parts):
        if not _is_allowed_example_snapshot(path):
            return f"private/generated directory: {normalized}"
    if path.name.endswith(".snapshot.json") and not _is_allowed_example_snapshot(path):
        return f"non-example snapshot: {normalized}"
    return None


def m6_retired_tree_assertion(root: Path) -> list[str]:
    """M6: the v2 production tree must not carry the Python oracle tree."""
    problems = []
    for relative in ("src/seattrellis", "native", "pyproject.toml"):
        if (root / relative).exists():
            problems.append(f"M6: retired Python tree still present: {relative}")
    return problems


def tracked_paths(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        check=True,
        capture_output=True,
    )
    return [
        value.decode("utf-8", errors="surrogateescape")
        for value in result.stdout.split(b"\0")
        if value
    ]


def archive_paths(path: Path) -> list[str]:
    if path.suffix == ".whl" or zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as archive:
            return archive.namelist()
    if tarfile.is_tarfile(path):
        with tarfile.open(path) as archive:
            return archive.getnames()
    raise ValueError(f"Unsupported archive format: {path}")


def find_problems(paths: list[str]) -> list[str]:
    return [problem for path in paths if (problem := _path_problem(path)) is not None]


def workspace_metadata(root: Path) -> list[str]:
    return [
        path.relative_to(root).as_posix()
        for path in root.rglob(".DS_Store")
        if ".git" not in path.relative_to(root).parts
    ]


def unsafe_documentation_images(root: Path, paths: list[str]) -> list[str]:
    problems = []
    for relative in paths:
        parts = PurePosixPath(relative).parts
        if not parts or parts[0] not in {"docs", "website"}:
            continue
        path = root / relative
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        if suffix in FORBIDDEN_IMAGE_SUFFIXES:
            problems.append(f"unsafe documentation image extension: {relative}")
            continue
        try:
            signature = _unsafe_image_format(path.read_bytes()[:32])
        except OSError as error:
            problems.append(f"cannot inspect tracked file {relative}: {error}")
            continue
        if signature is not None:
            problems.append(
                f"unsafe documentation image signature ({signature}): {relative}"
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--archive",
        action="append",
        default=[],
        type=Path,
        help="Also inspect a wheel, zip, or source distribution.",
    )
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]

    tracked = tracked_paths(root)
    problems = [
        *(f"tracked: {item}" for item in find_problems(tracked)),
        *unsafe_documentation_images(root, tracked),
        *(f"workspace metadata: {item}" for item in workspace_metadata(root)),
    ]
    for archive in args.archive:
        problems.extend(
            f"{archive}: {item}" for item in find_problems(archive_paths(archive))
        )

    if problems:
        print("Repository hygiene check failed:", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        return 1

    checked = len(args.archive)
    suffix = f" and {checked} archive(s)" if checked else ""
    print(f"Repository hygiene check passed for tracked files{suffix}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
