from __future__ import annotations

from html import escape
from pathlib import Path

from seattrellis.models.snapshot import SeatingSnapshot


def export_html(snapshot: SeatingSnapshot, output: str | Path) -> Path:
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render_html(snapshot), encoding="utf-8")
    return path


def _render_html(snapshot: SeatingSnapshot) -> str:
    min_row, max_row, min_col, max_col = _bounds(snapshot)
    assignment_by_seat = {assignment.seat_id: assignment for assignment in snapshot.assignments}
    seat_by_position = {(seat.row, seat.col): seat for seat in snapshot.layout.seats}
    rows_html: list[str] = []
    for row in range(min_row, max_row + 1):
        cells: list[str] = []
        for col in range(min_col, max_col + 1):
            seat = seat_by_position.get((row, col))
            if seat is None:
                cells.append('<td class="empty"></td>')
                continue
            assignment = assignment_by_seat.get(seat.seat_id)
            classes = "seat disabled" if not seat.enabled else "seat"
            name = escape(assignment.student_name if assignment else "")
            cells.append(
                f'<td class="{classes}"><div class="seat-id">{escape(seat.seat_id)}</div>'
                f'<div class="student">{name if seat.enabled else "--"}</div></td>'
            )
        rows_html.append("<tr>" + "".join(cells) + "</tr>")

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>{escape(snapshot.layout.name)} SeatTrellis</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 32px; color: #111; }}
    h1 {{ font-size: 24px; margin-bottom: 8px; }}
    .meta {{ color: #555; margin-bottom: 20px; }}
    table {{ border-collapse: separate; border-spacing: 8px; }}
    td {{ width: 140px; height: 76px; text-align: center; vertical-align: middle; border-radius: 8px; }}
    .seat {{ background: #eaf4ff; border: 1px solid #3b82f6; }}
    .disabled, .empty {{ background: #f2f2f2; border: 1px solid #ccc; color: #777; }}
    .seat-id {{ font-size: 12px; color: #555; margin-bottom: 8px; }}
    .student {{ font-weight: 700; }}
  </style>
</head>
<body>
  <h1>{escape(snapshot.layout.name)}</h1>
  <div class="meta">Generated by SeatTrellis at {escape(str(snapshot.created_at))}</div>
  <table>
    {"".join(rows_html)}
  </table>
</body>
</html>
"""


def _bounds(snapshot: SeatingSnapshot) -> tuple[int, int, int, int]:
    rows = [seat.row for seat in snapshot.layout.seats]
    cols = [seat.col for seat in snapshot.layout.seats]
    return min(rows), max(rows), min(cols), max(cols)
