#![recursion_limit = "256"]

//! xtask: development-only task runner (M1-06).
//!
//! Subcommands:
//! - `xtask contract openapi` — write `docs/api-v1-openapi.json` from the
//!   declarative spec (`spec.rs`, the single source of truth for the wire
//!   surface).
//! - `xtask contract ts`      — write `clients/web/src/api/generated.ts`, a
//!   typed fetch client (Bearer session header included).
//! - `xtask contract check`   — regenerate both into a temp dir and compare
//!   byte-for-byte with the committed artifacts; exit non-zero on drift
//!   (wired into CI so spec and generated files can never diverge).
//!
//! Usage: `cargo run -p xtask -- contract <openapi|ts|check>`

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

mod spec;

use schemars::JsonSchema;
use seattrellis_schema::dto::bundle_manifest::ProjectBundleManifest;
use seattrellis_schema::dto::classroom_layout::ClassroomLayout;
use seattrellis_schema::dto::student_roster::StudentRoster;
use seattrellis_schema::{ArtifactEnvelope, ArtifactKind};

const OPENAPI_OUT: &str = "docs/api-v1-openapi.json";
const TS_OUT: &str = "clients/web/src/api/generated.ts";
/// Generated v2 artifact schemas (M2-02): one file per kind, describing the
/// full envelope document for that artifact.
const SCHEMA_ARTIFACTS: &[(&str, ArtifactKind)] = &[
    ("student-roster", ArtifactKind::StudentRoster),
    ("classroom-layout", ArtifactKind::ClassroomLayout),
    ("project-bundle-manifest", ArtifactKind::ProjectBundleManifest),
];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives one level under the repo root")
        .to_path_buf()
}

fn write_artifact(relative: &str, content: &str) -> Result<(), String> {
    let path = repo_root().join(relative);
    fs::write(&path, content).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

/// Generate all v2 artifact JSON Schemas (one file per kind).
fn schema_artifacts() -> Vec<(String, String)> {
    SCHEMA_ARTIFACTS
        .iter()
        .map(|(slug, kind)| {
            let schema = match kind {
                ArtifactKind::StudentRoster => {
                    schema_for_envelope::<StudentRoster>(kind)
                }
                ArtifactKind::ClassroomLayout => {
                    schema_for_envelope::<ClassroomLayout>(kind)
                }
                ArtifactKind::ProjectBundleManifest => {
                    schema_for_envelope::<ProjectBundleManifest>(kind)
                }
                _ => unreachable!("schema artifacts are listed explicitly"),
            };
            (
                format!("schemas/{slug}.v2.schema.json"),
                serde_json::to_string_pretty(&schema).expect("schema serializes") + "\n",
            )
        })
        .collect()
}

/// Build the envelope schema for a typed payload via schemars.
fn schema_for_envelope<T: JsonSchema>(kind: &ArtifactKind) -> serde_json::Value {
    let root = schemars::schema_for!(ArtifactEnvelope<T>);
    let mut value = serde_json::to_value(root).expect("schema converts");
    // Record the artifact kind in the schema title so generated files are
    // self-describing and drift-checkable.
    value["title"] = serde_json::Value::String(format!("SeatTrellis v2 artifact: {kind:?}"));
    value
}

/// The committed OpenAPI document (pretty JSON).
fn openapi_document() -> String {
    let mut document = spec::spec();
    if let Some(components) = document.get_mut("components") {
        let _ = components;
    }
    serde_json::to_string_pretty(&document).expect("spec serializes") + "\n"
}

/// The generated TypeScript client: one typed function per endpoint, plus the
/// DTO interfaces. The session token is injected via `setSessionToken`.
fn typescript_client() -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `cargo run -p xtask -- contract ts` — DO NOT EDIT.\n\
         // Source of truth: xtask/src/spec.rs (M1-06).\n\
         // Typed companion for the loopback API. The workbench (client.ts)\n\
         // remains the wired client; this file is the drift-checked contract\n\
         // seed that M6 converges onto.\n\n",
    );
    out.push_str("let sessionToken: string | null = null;\n\n");
    out.push_str("export function setSessionToken(token: string | null): void {\n  sessionToken = token;\n}\n\n");
    out.push_str(
        "async function call<T>(path: string, init?: RequestInit): Promise<T> {\n\
         \x20 const headers = new Headers(init?.headers);\n\
         \x20 headers.set(\"Accept\", \"application/json\");\n\
         \x20 if (sessionToken) headers.set(\"Authorization\", `Bearer ${sessionToken}`);\n\
         \x20 const response = await fetch(path, { ...init, headers });\n\
         \x20 if (!response.ok) {\n\
         \x20   throw new Error(`SeatTrellis API ${response.status}: ${await response.text()}`);\n\
         \x20 }\n\
         \x20 return (await response.json()) as T;\n\
         }\n\n",
    );
    out.push_str("export const API_ROOT = \"/api/v1\";\n\n");
    out.push_str(interfaces());

    for (name, signature) in endpoints() {
        out.push_str(&signature);
        out.push('\n');
        let _ = name;
    }
    out
}

/// DTO interfaces mirrored from the spec's component schemas. The generator
/// is the single source of truth (spec.rs + this emitter); the wire shapes
/// stay accurate until M2-01 lands fully typed DTOs.
fn interfaces() -> &'static str {
    r#"export interface HealthResponse {
  api_version: string;
  service: string;
  status: string;
}

export interface SessionResponse {
  api_version: number;
  session_token: string;
}

export interface CoreSolveRequest {
  api_version: number;
  student_count: number;
  seat_positions: number[][];
  edges?: number[][];
  fixed_seats?: number[][];
  must_be_adjacent?: number[][];
  cannot_be_adjacent?: number[][];
  min_distance?: unknown[];
  seed?: number;
  students?: unknown[];
  rules?: Record<string, unknown>;
  layout?: Record<string, unknown>;
  history?: Record<string, unknown>;
  pair_history?: Record<string, unknown>;
}

export interface GenerateClassRequest {
  draft: {
    students: unknown[];
    room: { template_id?: string; layout?: Record<string, unknown> };
    goal: Record<string, unknown>;
    history_snapshots?: unknown[];
  };
  options?: { seed?: number; candidate_count?: number };
}

export interface CandidateSummary {
  candidate_id: string;
  recommended: boolean;
  total_score: number;
}

export interface GenerateClassResponse {
  class_name: string;
  goal: string;
  warnings: string[];
  recommended_candidate_id: string;
  candidates: CandidateSummary[];
  editor: EditorState;
}

export interface EditorStudentState {
  student_key: string;
  display_name: string;
  seat_id?: string;
  locked: boolean;
}

export interface EditorSeatState {
  seat_id: string;
  [key: string]: unknown;
}

export interface EditorState {
  kind: string;
  protocol_version: string;
  draft_id: string;
  revision: number;
  candidate_id?: string;
  undo_depth: number;
  redo_depth: number;
  students: EditorStudentState[];
  seats: EditorSeatState[];
}

export interface EditorCommandEnvelope {
  kind: string;
  protocol_version: string;
  command_id: string;
  draft_id: string;
  base_revision: number;
  action: string;
  operations?: unknown[];
}

export interface ExportDraftRequest {
  draft_id: string;
  format: "svg" | "html" | "print-html" | "png" | "pdf" | "excel" | "docx" | "pptx";
  template?: string;
  privacy?: string;
  orientation?: string;
  page_scale?: number;
  locale?: string;
  show_student_ids?: boolean;
}
"#
}

/// (endpoint name, generated function source)
fn endpoints() -> Vec<(&'static str, String)> {
    vec![
        (
            "health",
            r#"export async function health(): Promise<HealthResponse> {
  return call<HealthResponse>(`${API_ROOT}/health`);
}"#
            .to_string(),
        ),
        (
            "session",
            r#"export async function fetchSession(): Promise<SessionResponse> {
  return call<SessionResponse>(`${API_ROOT}/session`);
}"#
            .to_string(),
        ),
        (
            "generateClass",
            r#"export async function generateClass(
  request: GenerateClassRequest | CoreSolveRequest,
): Promise<GenerateClassResponse> {
  return call<GenerateClassResponse>(`${API_ROOT}/classes/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(request),
  });
}"#
            .to_string(),
        ),
        (
            "fetchEditorState",
            r#"export async function fetchEditorState(
  draftId: string,
): Promise<EditorState> {
  return call<EditorState>(`${API_ROOT}/editing/drafts/${draftId}`);
}"#
            .to_string(),
        ),
        (
            "dispatchEditorCommand",
            r#"export async function dispatchEditorCommand(
  draftId: string,
  command: EditorCommandEnvelope,
): Promise<EditorState> {
  return call<EditorState>(`${API_ROOT}/editing/drafts/${draftId}/commands`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(command),
  });
}"#
            .to_string(),
        ),
        (
            "exportDraft",
            r#"export async function exportDraft(
  request: ExportDraftRequest,
): Promise<Blob> {
  const response = await fetch(`${API_ROOT}/exports`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
    },
    body: JSON.stringify(request),
  });
  if (!response.ok) throw new Error(`SeatTrellis API ${response.status}`);
  return response.blob();
}"#
            .to_string(),
        ),
        (
            "listRecentProjects",
            r#"export async function listRecentProjects(
  root?: string,
  limit = 20,
): Promise<unknown> {
  const query = new URLSearchParams({ limit: String(limit) });
  if (root) query.set("root", root);
  return call<unknown>(`${API_ROOT}/projects/recent?${query}`);
}"#
            .to_string(),
        ),
    ]
}

/// Regenerate the artifacts into `target/xtask-check` and compare with the
/// committed files; return the list of drifted paths.
fn check_drift() -> Vec<String> {
    let root = repo_root();
    let tmp = root.join("target").join("xtask-check");
    let _ = fs::remove_dir_all(&tmp);
    fs::create_dir_all(&tmp).expect("temp dir");

    let mut artifacts: Vec<(&str, String)> = vec![
        (OPENAPI_OUT, openapi_document()),
        (TS_OUT, typescript_client()),
    ];
    for (relative, content) in schema_artifacts() {
        artifacts.push((Box::leak(relative.into_boxed_str()), content));
    }
    let mut drifted = Vec::new();
    for (relative, content) in artifacts {
        let committed = root.join(relative);
        let fresh_path = tmp.join(relative.replace('/', "__"));
        fs::write(&fresh_path, &content).expect("write temp artifact");
        let matches = match fs::read(&committed) {
            Ok(existing) => existing == content.as_bytes(),
            Err(_) => false,
        };
        if !matches {
            drifted.push(relative.to_string());
        }
    }
    drifted
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let Some(command) = args.first() else {
        eprintln!("usage: xtask contract <openapi|ts|check>");
        return ExitCode::from(2);
    };
    match command.as_str() {
        "contract" => match args.get(1).map(String::as_str) {
            Some("openapi") => {
                let content = openapi_document();
                match write_artifact(OPENAPI_OUT, &content) {
                    Ok(()) => {
                        println!("wrote {OPENAPI_OUT}");
                        ExitCode::SUCCESS
                    }
                    Err(message) => {
                        eprintln!("{message}");
                        ExitCode::FAILURE
                    }
                }
            }
            Some("ts") => {
                let content = typescript_client();
                match write_artifact(TS_OUT, &content) {
                    Ok(()) => {
                        println!("wrote {TS_OUT}");
                        ExitCode::SUCCESS
                    }
                    Err(message) => {
                        eprintln!("{message}");
                        ExitCode::FAILURE
                    }
                }
            }
            Some("schemas") => {
                let mut failures = 0;
                for (relative, content) in schema_artifacts() {
                    match write_artifact(&relative, &content) {
                        Ok(()) => println!("wrote {relative}"),
                        Err(message) => {
                            eprintln!("{message}");
                            failures += 1;
                        }
                    }
                }
                if failures == 0 {
                    ExitCode::SUCCESS
                } else {
                    ExitCode::FAILURE
                }
            }
            Some("check") => {
                let drifted = check_drift();
                if drifted.is_empty() {
                    println!("contract artifacts are up to date");
                    ExitCode::SUCCESS
                } else {
                    eprintln!("contract drift detected (run `cargo run -p xtask -- contract openapi ts`):");
                    for path in drifted {
                        eprintln!("- {path}");
                    }
                    ExitCode::FAILURE
                }
            }
            _ => {
                eprintln!("unknown contract subcommand; expected openapi|ts|check");
                ExitCode::from(2)
            }
        },
        _ => {
            eprintln!("unknown xtask command; expected `contract`");
            ExitCode::from(2)
        }
    }}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every generated artifact schema must itself validate against the
    /// draft-07 metaschema (M2-02 exit gate: metaschema 校验).
    #[test]
    fn generated_schemas_validate_against_the_metaschema() {
        // Vendored copy of https://json-schema.org/draft-07/schema so the
        // check runs offline in CI.
        let metaschema: serde_json::Value = serde_json::from_str(include_str!(
            "../fixtures/draft-07-metaschema.json"
        ))
        .expect("vendored metaschema parses");
        let validator = jsonschema::validator_for(&metaschema).expect("metaschema is valid");
        for (relative, content) in schema_artifacts() {
            let document: serde_json::Value =
                serde_json::from_str(&content).expect("generated schema parses");
            let result = validator.validate(&document);
            assert!(
                result.is_ok(),
                "{relative} is not a valid draft-07 schema: {}",
                result.err().map(|error| error.to_string()).unwrap_or_default(),
            );
        }
    }

    /// The generated schemas must reject a document with an unknown field in
    /// the payload (the strict-parse contract, expressed in the schema).
    #[test]
    fn generated_student_roster_schema_rejects_unknown_fields() {
        let (_, content) = schema_artifacts()
            .into_iter()
            .find(|(name, _)| name == "schemas/student-roster.v2.schema.json")
            .expect("student roster schema is generated");
        let schema: serde_json::Value = serde_json::from_str(&content).unwrap();
        let validator = jsonschema::validator_for(&schema).unwrap();
        let good = serde_json::json!({
            "kind": "student_roster",
            "schema_version": 2,
            "data": { "students": [ { "student_id": "S1", "name": "Alice" } ] }
        });
        assert!(validator.validate(&good).is_ok());
        let bad = serde_json::json!({
            "kind": "student_roster",
            "schema_version": 2,
            "data": { "students": [ { "student_id": "S1", "mystery": 1 } ] }
        });
        assert!(
            validator.validate(&bad).is_err(),
            "unknown payload fields must be rejected by the generated schema"
        );
    }
}
